# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d9263fcb46cffcf7b9451134c6991f24189d1d6ae0b26fa3d535bd79379d84bf630eabdbcb5b33168f315c3044a14c6e28b761dab170f3fe72ab8e165c5e76

test:
  secret_key_base: 255b3dbd7253550b202b4c312f354da172a59864ebdfcb0b946b2a9d978fd4b77b8ff737b2b4981b418c2c57a867f0c344d7235d8b0afaae246384c8afba58e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
